minimum_pre_commit_version: 2.15.0
exclude: ^LICENSES/|\.(html|csv|svg)$

repos:
  # Moved to ruff-format
  # - repo: local
  #   hooks:
  #     # NOTE: we make `black` a local hook because if it's installed from
  #     # PyPI (rather than from source) then it'll run twice as fast thanks to mypyc
  #     - id: black
  #       name: black
  #       description: "Black: The uncompromising Python code formatter"
  #       entry: black
  #       language: python
  #       require_serial: true
  #       types_or: [python, pyi]
  #       additional_dependencies: [black==23.3.0]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/jendrikseipp/vulture
    rev: "v2.7"
    hooks:
      - id: vulture
        entry: python scripts/run_vulture.py
        pass_filenames: true
        require_serial: false
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        types_or: [python, rst, markdown, cython, c]
        additional_dependencies: [tomli]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: \.txt$
      - id: trailing-whitespace
  # Commenting this out till
  # - repo: https://github.com/PyCQA/isort
  #   rev: 5.12.0
  #   hooks:
  #     - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
